/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    page: Page;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    page: PageSelect<false> | PageSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  aspect?: ('landscape' | 'portrait' | 'square') | null;
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page".
 */
export interface Page {
  id: number;
  title: string;
  country: 'ke' | 'tz' | 'mz' | 'cbv' | 'stm';
  'theme color'?: string | null;
  'core values'?: string | null;
  /**
   * Add all required fields and save to autogenerate
   */
  url: string;
  'operating hours'?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  operatingHours_html?: string | null;
  seo: {
    /**
     * 50 - 60 characters
     */
    'meta title': string;
    /**
     * 70 - 150 characters
     */
    'meta description': string;
    'search console': string;
    analytics: string;
  };
  navigation: {
    logo?: (number | null) | Media;
    menuItems: {
      'anchor name': string;
      /**
       * The ID of the section this menu item links to (without the # symbol)
       */
      'anchor id': 'home' | 'about' | 'services' | 'contact' | 'products';
      style?: ('default' | 'primary' | 'secondary') | null;
      id?: string | null;
    }[];
  };
  hero?:
    | (
        | {
            heading: string;
            excerpt: string;
            cover: number | Media;
            type?:
              | (
                  | 'default'
                  | 'horizontal'
                  | 'vertical'
                  | 'stylised horizontal'
                  | 'alternate vertical'
                  | 'fullscreen'
                  | 'alternate fullscreen'
                  | 'split'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'simple-hero';
          }
        | {
            heading: string;
            excerpt: string;
            slides?:
              | {
                  cover: number | Media;
                  id?: string | null;
                }[]
              | null;
            type?:
              | (
                  | 'default'
                  | 'horizontal'
                  | 'vertical'
                  | 'stylised horizontal'
                  | 'alternate vertical'
                  | 'fullscreen'
                  | 'alternate fullscreen'
                  | 'split'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slideshow-hero';
          }
      )[]
    | null;
  content?:
    | (
        | {
            title: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            description_html?: string | null;
            highlight?: boolean | null;
            testimonies?:
              | {
                  testimony: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  title: string;
                  testimony_html?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carousel-testimonial';
          }
        | {
            title: string;
            /**
             * The ID of the section this menu item links to (without the # symbol)
             */
            'anchor id'?: ('home' | 'about' | 'services' | 'contact' | 'products') | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            body_html?: string | null;
            highlight?: boolean | null;
            'card type'?: ('basic' | 'alternating' | 'alternating basic') | null;
            'card grid'?:
              | {
                  image?: (number | null) | Media;
                  title: string;
                  body?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  body_html?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-with-grid';
          }
        | {
            title: string;
            /**
             * The ID of the section this menu item links to (without the # symbol)
             */
            'anchor id'?: ('home' | 'about' | 'services' | 'contact' | 'products') | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            body_html?: string | null;
            image: number | Media;
            position?: ('left' | 'right' | 'bottom' | 'top') | null;
            highlight?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-with-media';
          }
        | {
            title: string;
            body: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            body_html?: string | null;
            images: {
              image?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-grid-cta';
          }
        | {
            title: string;
            /**
             * The ID of the section this menu item links to (without the # symbol)
             */
            'anchor id'?: ('home' | 'about' | 'services' | 'contact' | 'products') | null;
            excerpt: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            excerpt_html?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            body_html?: string | null;
            image: number | Media;
            highlight?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rounded-about';
          }
        | {
            heading: string;
            description: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            descritpion_html?: string | null;
            buttonText: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'simple-call-to-action';
          }
        | {
            title: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            description_html?: string | null;
            highlight?: boolean | null;
            testimonies?:
              | {
                  testimony: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  title: string;
                  testimony_html?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'simple-testimonial';
          }
        | {
            title: string;
            /**
             * The ID of the section this menu item links to (without the # symbol)
             */
            'anchor id'?: ('home' | 'about' | 'services' | 'contact' | 'products') | null;
            excerpt: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            excerpt_html?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            body_html?: string | null;
            image: number | Media;
            highlight?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'symbiotic-about';
          }
        | {
            title: string;
            body: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            body_html?: string | null;
            images: {
              image?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'two-image-cta';
          }
        | {
            title: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            description_html?: string | null;
            image?: (number | null) | Media;
            highlight?: boolean | null;
            options: {
              title: string;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              description_html?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-choose-us-column';
          }
        | {
            title: string;
            description: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            description_html?: string | null;
            highlight?: boolean | null;
            options: {
              icon: string;
              title: string;
              body: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              body_html?: string | null;
              id?: string | null;
            }[];
            colored?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-choose-us-grid';
          }
        | {
            title: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            description_html?: string | null;
            highlight?: boolean | null;
            options: {
              title: string;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              description_html?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-choose-us-interactive';
          }
      )[]
    | null;
  contact?:
    | {
        title: string;
        contact: {
          phone: {
            number: string;
            type?: ('mobile' | 'whatsapp' | 'telephone') | null;
            id?: string | null;
          }[];
          email: {
            email: string;
            id?: string | null;
          }[];
        };
        location: {
          address: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          iframe: string;
          address_html?: string | null;
        };
        direction?: ('vertical' | 'horizontal' | 'overlap') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'simple-contact';
      }[]
    | null;
  'social links'?:
    | {
        url: string;
        title: string;
        platform?:
          | (
              | 'facebook'
              | 'instagram'
              | 'x (formerly twitter)'
              | 'linkedin'
              | 'youtube'
              | 'pinterest'
              | 'tiktok'
              | 'telegram'
              | 'whatsapp'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  'footer style'?: ('default' | 'tiny') | null;
  /**
   * Add all required fields and save to autogenerate
   */
  'Company url': string;
  /**
   * Add all required fields and save to autogenerate
   */
  'Company Name': string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'page';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  aspect?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_select".
 */
export interface PageSelect<T extends boolean = true> {
  title?: T;
  country?: T;
  'theme color'?: T;
  'core values'?: T;
  url?: T;
  'operating hours'?: T;
  operatingHours_html?: T;
  seo?:
    | T
    | {
        'meta title'?: T;
        'meta description'?: T;
        'search console'?: T;
        analytics?: T;
      };
  navigation?:
    | T
    | {
        logo?: T;
        menuItems?:
          | T
          | {
              'anchor name'?: T;
              'anchor id'?: T;
              style?: T;
              id?: T;
            };
      };
  hero?:
    | T
    | {
        'simple-hero'?:
          | T
          | {
              heading?: T;
              excerpt?: T;
              cover?: T;
              type?: T;
              id?: T;
              blockName?: T;
            };
        'slideshow-hero'?:
          | T
          | {
              heading?: T;
              excerpt?: T;
              slides?:
                | T
                | {
                    cover?: T;
                    id?: T;
                  };
              type?: T;
              id?: T;
              blockName?: T;
            };
      };
  content?:
    | T
    | {
        'carousel-testimonial'?:
          | T
          | {
              title?: T;
              description?: T;
              description_html?: T;
              highlight?: T;
              testimonies?:
                | T
                | {
                    testimony?: T;
                    title?: T;
                    testimony_html?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'content-with-grid'?:
          | T
          | {
              title?: T;
              'anchor id'?: T;
              body?: T;
              body_html?: T;
              highlight?: T;
              'card type'?: T;
              'card grid'?:
                | T
                | {
                    image?: T;
                    title?: T;
                    body?: T;
                    body_html?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'content-with-media'?:
          | T
          | {
              title?: T;
              'anchor id'?: T;
              body?: T;
              body_html?: T;
              image?: T;
              position?: T;
              highlight?: T;
              id?: T;
              blockName?: T;
            };
        'image-grid-cta'?:
          | T
          | {
              title?: T;
              body?: T;
              body_html?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rounded-about'?:
          | T
          | {
              title?: T;
              'anchor id'?: T;
              excerpt?: T;
              excerpt_html?: T;
              body?: T;
              body_html?: T;
              image?: T;
              highlight?: T;
              id?: T;
              blockName?: T;
            };
        'simple-call-to-action'?:
          | T
          | {
              heading?: T;
              description?: T;
              descritpion_html?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        'simple-testimonial'?:
          | T
          | {
              title?: T;
              description?: T;
              description_html?: T;
              highlight?: T;
              testimonies?:
                | T
                | {
                    testimony?: T;
                    title?: T;
                    testimony_html?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'symbiotic-about'?:
          | T
          | {
              title?: T;
              'anchor id'?: T;
              excerpt?: T;
              excerpt_html?: T;
              body?: T;
              body_html?: T;
              image?: T;
              highlight?: T;
              id?: T;
              blockName?: T;
            };
        'two-image-cta'?:
          | T
          | {
              title?: T;
              body?: T;
              body_html?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-choose-us-column'?:
          | T
          | {
              title?: T;
              description?: T;
              description_html?: T;
              image?: T;
              highlight?: T;
              options?:
                | T
                | {
                    title?: T;
                    description?: T;
                    description_html?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-choose-us-grid'?:
          | T
          | {
              title?: T;
              description?: T;
              description_html?: T;
              highlight?: T;
              options?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    body_html?: T;
                    id?: T;
                  };
              colored?: T;
              id?: T;
              blockName?: T;
            };
        'why-choose-us-interactive'?:
          | T
          | {
              title?: T;
              description?: T;
              description_html?: T;
              highlight?: T;
              options?:
                | T
                | {
                    title?: T;
                    description?: T;
                    description_html?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  contact?:
    | T
    | {
        'simple-contact'?:
          | T
          | {
              title?: T;
              contact?:
                | T
                | {
                    phone?:
                      | T
                      | {
                          number?: T;
                          type?: T;
                          id?: T;
                        };
                    email?:
                      | T
                      | {
                          email?: T;
                          id?: T;
                        };
                  };
              location?:
                | T
                | {
                    address?: T;
                    iframe?: T;
                    address_html?: T;
                  };
              direction?: T;
              id?: T;
              blockName?: T;
            };
      };
  'social links'?:
    | T
    | {
        url?: T;
        title?: T;
        platform?: T;
        id?: T;
      };
  'footer style'?: T;
  'Company url'?: T;
  'Company Name'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}